"""init

Revision ID: 1315168a4dd1
Revises: 
Create Date: 2023-07-04 15:19:05.590377

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1315168a4dd1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retainstatus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_retainstatus'))
    )
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trader_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_client_trader_id_trader'), 'trader', ['trader_id'], ['id'])

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_employee_login'), ['login'])

    with op.batch_alter_table('trader', schema=None) as batch_op:
        batch_op.add_column(sa.Column('surname', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('accountNumber', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('mainBalance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('bonuses', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('credFacilities', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('accountStatus', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('blocked', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('isActive', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('isVipStatus', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('autologin', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('autologin_link', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('status_id', sa.Integer(), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('balance',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(batch_op.f('fk_trader_status_id_retainstatus'), 'retainstatus', ['status_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trader', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_trader_status_id_retainstatus'), type_='foreignkey')
        batch_op.alter_column('balance',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('status_id')
        batch_op.drop_column('autologin_link')
        batch_op.drop_column('autologin')
        batch_op.drop_column('isVipStatus')
        batch_op.drop_column('isActive')
        batch_op.drop_column('blocked')
        batch_op.drop_column('accountStatus')
        batch_op.drop_column('credFacilities')
        batch_op.drop_column('bonuses')
        batch_op.drop_column('mainBalance')
        batch_op.drop_column('accountNumber')
        batch_op.drop_column('country')
        batch_op.drop_column('password')
        batch_op.drop_column('date')
        batch_op.drop_column('surname')

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_employee_login'), type_='unique')

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_client_trader_id_trader'), type_='foreignkey')
        batch_op.drop_column('trader_id')

    op.drop_table('retainstatus')
    # ### end Alembic commands ###
